---
- hosts: all
  become: yes
  tasks:
  - name: install httpd  web server into amezon linx server
    yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"

  - name: start apache2 service
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat"