---
- hosts: all
  become: yes
  tasks:
  - name: install jdk into ubuntu20
    apt:
     name: openjdk-8-jre-headless
     state: present
    when: ansible_os_family == "Debian"

  - name: instal jdk on amezon linux  
    yum:
     name: java-1.8.0-openjdk
     state: present
    when: ansible_os_family == "RedHat"