---
- hosts: webservers
  become: yes
  tasks:
  - name: install jdk8 in ubuntu20 node1
    apt: 
     name: "{{ myjdkonubuntu }}"
     state: present
    when: ansible_os_family == "Debian"
  
  - name: install jdk8 on amezonlinux node2
    yum:
     name: "{{ myjdkonamezonos }}"
     state: present
    when: ansible_os_family == "RedHat"