---
- hosts: all
  become: yes
  tasks:
  - name: install  apache2 web server in ubuntu20
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"
  
  - name: start the apache2 service
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"

  - name: install httpd  web server into amezon linx server
    yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"

  - name: start apache2 service
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat"